language: android  # 构建语言

sudo: false  # 开启基于容器的Travis CI任务，让编译效率更高。

dist: precise

notifications:      # 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置false吧
  email: false

jdk:
  - oraclejdk8
  
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.3
    - android-25

licenses:
   - 'android-sdk-preview-license-52d11cd2'
   - 'android-sdk-license-.+'
   
before_install:     
 - chmod +x gradlew  # 改变gradlew的访问权限
  
script:              # 执行:下面的命令
  - ./gradlew assemble

